### ISSUE TITLE
jupyter-manim and ManimCommunity

### ISSUE THREAD

**Issue by kolibril13** [krassowski/jupyter-manim#26]
Hi @krassowski,
At the moment, some people (including me) are hardly working on making manim more user-friendly in the manim-community repo: https://github.com/ManimCommunity/manim

We are actively developing new versions which are quite good by now, and we are also thinking about improving the jupyter notebook support.
Therefore I have an unusual question:
How would you feel to transfer the jupyter-manim repo to the manim-community Github Organization?
We would then try to enhance some features, and even maybe add a new java-script renderer.
Self-explanatory we would give you credits and that you created this repo first place, and keep a MIT license.

**Comment by krassowski** [comment]
Hi! Thanks for reaching out. Some quick questions:
- What would be the scope of jupyter-manim after moving the repo?
- Would it support all three versions of manim as listed [in here](https://github.com/3b1b/manim/issues/1243)?
- Where can I learn more about the JavaScript renderer?
- Have you considered making the Jupyter support a built-in feature in ManimCommunity/manim? This package is built on a workaround because the necessary interface is not exposed in manim but when building anew, I do not see a need for it at all. A simple magic definition (run conditionally on IPython presence) would suffice, and it would be even better to have it built-in rather than require users to install a new package. I would then be happy to mention this in the readme and maybe even archive this project if your project would take over manim and users would get confused (however there is the question of the GPU version of manim which would probably still need this package).

**Comment by kolibril13** [comment]
Thanks for the quick reply.
To your questions:
1. The ManimCoumunity Organization has about a dozen devs, and I would say that at about 3 of us would be interested in improving the jupyter-manim functionalities. Spontaneously, it is hard to say how big the scope will be, but my vision would be a version that is straight forward to install, stable to use, and probably even web compatible (e.g. google collab). I will forward this threat to some other people, so they can join this exchange of ideas. 
2.  The focus would be definitely on the ManimCommunity/manim repo. The master branch of 3b1b/manim won't be supported, and how/if the shadders branch I can not say. I think there were already ideas to add GPU rendering like on the shadders branch to ManimCoumunity, but probably not very soon. 
3. The JavaScript renderer for manim community can be used by running it with the `--use_js_renderer` flag when the instructions from https://github.com/ManimCommunity/manim-renderer are performed, it is quite new and there is not yet a big tutorial, but I'll attach a video to this post to get a feeling how it looks like.
4. Making it built-in sounds like a good and reasonable idea. Probably we should first think about point number 2 and then think about this question. And thanks for your awareness of making things as non-confusing as possible for the users and your offer to archive (or maybe rename?) this jupyter-manim project.

https://user-images.githubusercontent.com/44469195/103444443-8238c380-4c68-11eb-8417-d353fba50f70.mp4

**Comment by behackl** [comment]
> Have you considered making the Jupyter support a built-in feature in ManimCommunity/manim? This package is built on a workaround because the necessary interface is not exposed in manim but when building anew, I do not see a need for it at all. A simple magic definition (run conditionally on IPython presence) would suffice, and it would be even better to have it built-in rather than require users to install a new package.

We haven't thought of it so far, but I fully agree: not requiring users to install an additional package for access to a helpful Jupyter cell magic is probably the best approach. I'll open an issue over at ManimCommunity/manim (edit: https://github.com/ManimCommunity/manim/issues/895) to keep track of this idea, and actually I would also like to have this implemented rather sooner than later.

> I would then be happy to mention this in the readme and maybe even archive this project if your project would take over manim and users would get confused (however there is the question of the GPU version of manim which would probably still need this package).

Thank you very much! Once we are ready, it would be great if you could mention it in the readme. And yes, as @kolibril13 already mentioned, we currently don't support Grant's `shader` branch (and don't have something similar yet™️ in the community version). In order to support this, people will still require your `jupyter_manim` package.

**Comment by naveen521kk** [comment]
Isn't this issue fixed?

**Comment by kolibril13** [comment]
yes, it is! 👍🏼
